### ISSUE TITLE
model-ai cannot get

### ISSUE THREAD

**Issue by luoyh21** [THUAI-ssast/hiper-backend#37]
在当前分支中，所有有关ai的请求都会返回
failed to assign association &model.User{Model:gorm.Model{ID:0x0, CreatedAt:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), UpdatedAt:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletedAt:gorm.DeletedAt{Time:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Valid:false}}, AvatarURL:"", Bio:"", Department:"", Email:"", Name:"", Nickname:"", Password:[]uint8(nil), Permissions:model.GlobalPermissions{CanCreateGameOrContest:false}, School:"", Username:"admin", GameAdmins:[]model.Game(nil), ContestAdmins:[]model.Contest(nil), ContestRegistered:[]model.Contest(nil)}, make sure foreign fields exists
[0m[33m[2.139ms] [34;1m[rows:1][0m SELECT * FROM "ais" WHERE "base_contest_id" = '1' AND "user_id" = 1 AND "ais"."deleted_at" IS NULL ORDER BY id DESC LIMIT 20
从而无法获取

**Comment by Ethkuil** [comment]
关于这个 Issue，建议先看一下数据库里的实际情况……如 ais表 和 users表。

检查代码没检查出问题……我完善了一些约束、注释之类的。

问题还没解决的话可试试重建数据库。

**Comment by luoyh21** [comment]
已经重建所有数据库了，仍有问题，数据库中有对应的ai，但ai, err := model.GetAiByID(uint(ai_id), true)就会这样报错。
我怀疑func addPreloadsForAi(tx *gorm.DB) *gorm.DB {
	return tx.Preload("Sdk", func(db *gorm.DB) *gorm.DB {
		return db.Select("id", "name")
	}).**Preload("User", func(db *gorm.DB) *gorm.DB {
		return db.Select("avatar_url", "nickname", "username")
	})**
}有问题

**Comment by Ethkuil** [comment]
有 Preload 的不止 Ai，甚至 GetGames, User.GetContestRegistered, GetMatches,... 这些都有 Preload。我仔细对比了下实在没找出差别……其他数据模型会出现类似的问题吗？

**Comment by luoyh21** [comment]
match在获取时不会报错，但其没有获得User项，哪怕preload为true。这可能是正常的，但它和ai是唯二连续使用两次preload，即
return db.Select("id").Preload("Sdk", func(db *gorm.DB) *gorm.DB {
			return db.Select("id", "name")
		}).Preload("User", func(db *gorm.DB) *gorm.DB {
			return db.Select("avatar_url", "nickname", "username")
		})形式的了

**Comment by Ethkuil** [comment]
> match在获取时不会报错，但其没有获得User项，哪怕preload为true。这可能是正常的，但它和ai是唯二连续使用两次preload，即 return db.Select("id").Preload("Sdk", func(db *gorm.DB) *gorm.DB { return db.Select("id", "name") }).Preload("User", func(db *gorm.DB) *gorm.DB { return db.Select("avatar_url", "nickname", "username") })形式的了

好好好，破案了，我把 Preload 的层次写错了（

**Comment by luoyh21** [comment]
因此，目前GET /games/{id}/ais/{ai_id} 无法运行，由于
ai, err := model.GetAiByID(uint(ai_id), true)
	if err != nil {
		c.JSON(404, gin.H{"error": "AI not found"})
		return
	}
永远会报404，可以去检查一下

**Comment by luoyh21** [comment]
好，你更新下就行，model的其他地方应该都没有错
